# Generated by Django 5.1.15 on 2026-06-22 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('engine', 'Engine'), ('architecture', 'Architecture'), ('preprocessor', 'Preprocessor'), ('augmentation', 'Augmentation'), ('dataset_adapter', 'Dataset Adapter'), ('metric', 'Metric'), ('postprocessor', 'Postprocessor'), ('exporter', 'Exporter'), ('domain_pack', 'Domain Pack'), ('visualizer', 'Visualizer'), ('report', 'Report')], max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('field', models.CharField(choices=[('medical', 'Medical'), ('remote-sensing', 'Remote sensing'), ('materials', 'Materials'), ('generic', 'Generic')], default='generic', max_length=24)),
                ('author_handle', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in-review', 'In review'), ('published', 'Published')], default='draft', max_length=16)),
                ('official', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('license', models.CharField(max_length=64)),
                ('blurb', models.CharField(help_text='One-line summary for cards.', max_length=240)),
                ('long_description', models.TextField(blank=True, help_text="Markdown. The 'read about it' body.")),
                ('repo_url', models.URLField(blank=True, help_text='Git repo (source of record).')),
                ('dataset_url', models.URLField(blank=True, help_text='Hugging Face / dataset pointer.')),
                ('homepage_url', models.URLField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('cap_gpu', models.BooleanField(default=False)),
                ('cap_network', models.BooleanField(default=False)),
                ('cap_filesystem', models.CharField(choices=[('none', 'None'), ('read-only', 'Read-only'), ('read-write', 'Read-write')], default='read-only', max_length=16)),
                ('cap_data_access', models.CharField(choices=[('none', 'None'), ('masks-only', 'Masks only'), ('images-ro', 'Images (read-only)'), ('images-rw', 'Images (read-write)')], default='none', max_length=16)),
                ('hooks', models.JSONField(blank=True, default=list, help_text='Lifecycle hook names.')),
                ('deps', models.JSONField(blank=True, default=list, help_text='Dependency specifiers.')),
                ('installs', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithms', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='algorithms', to='algorithms.category')),
            ],
            options={
                'ordering': ['-installs', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semver, e.g. 1.4.2', max_length=32)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('line', models.CharField(blank=True, choices=[('current', 'Current'), ('', 'Stable'), ('deprecated', 'Deprecated')], default='', max_length=16)),
                ('tag', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch')], default='minor', max_length=8)),
                ('commit_sha', models.CharField(blank=True, help_text='Immutable source pointer.', max_length=64)),
                ('diff_summary', models.CharField(blank=True, help_text='e.g. +412 -96', max_length=64)),
                ('notes', models.JSONField(blank=True, default=list, help_text='Changelog bullet points.')),
                ('compat', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='algorithms.algorithm')),
            ],
            options={
                'ordering': ['-released_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='algorithm',
            index=models.Index(fields=['category', 'field'], name='algorithms__categor_567f52_idx'),
        ),
        migrations.AddIndex(
            model_name='algorithm',
            index=models.Index(fields=['status'], name='algorithms__status_9941b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('algorithm', 'version'), name='unique_algorithm_version'),
        ),
    ]
